/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#3f2e0a",
        "secondary-container": "#62422d",
        "secondary": "#ebbda2",
        "surface-container-lowest": "#170b08",
        "surface-container-high": "#352722",
        "on-secondary": "#462a17",
        "on-background": "#f7ddd6",
        "error": "#ffb4ab",
        "secondary-fixed": "#ffdbc7",
        "surface-dim": "#1d100c",
        "surface": "#1d100c",
        "on-primary-fixed": "#370d06",
        "inverse-surface": "#f7ddd6",
        "tertiary-fixed-dim": "#dfc393",
        "on-secondary-container": "#dcaf94",
        "outline": "#a08c89",
        "on-secondary-fixed-variant": "#83583bff",
        "on-surface-variant": "#d7c2bd",
        "inverse-on-surface": "#3c2d28",
        "on-secondary-fixed": "#2d1505",
        "on-tertiary-container": "#372705",
        "on-surface": "#f7ddd6",
        "on-primary": "#522218",
        "surface-container-highest": "#41312c",
        "inverse-primary": "#8a4e42",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#ebbda2",
        "on-tertiary-fixed": "#271900",
        "primary-fixed": "#ffdad3",
        "primary-container": "#c47f71",
        "surface-bright": "#463631",
        "background": "#1d100c",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#261814",
        "tertiary-container": "#a68d61",
        "tertiary": "#dfc393",
        "on-primary-container": "#491b12",
        "primary-fixed-dim": "#ffb4a5",
        "outline-variant": "#524340",
        "primary": "#ffb4a5",
        "on-primary-fixed-variant": "#6d372c",
        "surface-container": "#2a1c18",
        "surface-tint": "#ffb4a5",
        "surface-variant": "#41312c",
        "on-tertiary-fixed-variant": "#57441f",
        "tertiary-fixed": "#fcdfad",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
        sans: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
}
